name: Node.js CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '!*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: node-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-deps-
      - run: yarn install --frozen-lockfile
      - run: yarn format-check
      - run: yarn lint
