name: Fetch Ichika channel, and Ran channel

on:
  schedule:
  - cron: '2 2/3 * * *'

jobs:
  build:
    name: Indexing

    runs-on: ubuntu-latest

    steps:
    - uses: docker://inabagumi/pinkie:3.1
      with:
        args: --channel UC2kyQhzGOB-JPgcQX9OMgEw --channel UCRvpMpzAXBRKJQuk-8-Sdvg
      env:
        TZ: UTC
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_INDEX_NAME: prod_ANIMARE_SEARCH
