name: Indexing

on:
  schedule:
  - cron: '45 * * * *'

jobs:
  build:

    name: Run ytc

    runs-on: ubuntu-latest

    steps:

    - name: Setup Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Install ytc
      run: go get -u github.com/inabagumi/ytc

    - name: Run ytc
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        ALGOLIA_INDEX_NAME: prod_ANIMARE_SEARCH
      run: |
        $(go env GOPATH)/bin/ytc \
          -channel UC0Owc36U9lOyi9Gx9Ic-4qg \
          -channel UChqYnJlFxlBi6DfRz6jRenQ \
          -channel UC2kyQhzGOB-JPgcQX9OMgEw \
          -channel UCRvpMpzAXBRKJQuk-8-Sdvg
