name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Get yarn pnp unplugged directory path
        id: yarn-pnp-unplugged-dir-path
        run: echo "::set-output name=dir::$(yarn config get pnpUnpluggedFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-pnp-unplugged-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - run: yarn format-check
      - run: yarn lint
      - run: yarn test
