name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    env:
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm format-check
      - run: pnpm lint --filter './packages/*'
      - run: pnpm test
